### ISSUE TITLE
lanelet2anchors installation via pip

### ISSUE THREAD

**Issue by DrK2B** [FelixHertlein/lanelet2anchors#2]
When trying to install the package "lanelet2anchors" via pip by entering the command "pip install lanelet2anchors" into the terminal (under Windows), I receive the following error message:

ERROR: Could not find a version that satisfies the requirement lanelet2<2,>=1.2.1 (from lanelet2anchors) (from versions: none)
ERROR: No matching distribution found for lanelet2<2,>=1.2.1

I am grateful for any piece of support which could resolve this issue.
Thank you!

![image](https://github.com/FelixHertlein/lanelet2anchors/assets/104391285/d9b11ce6-3861-4f62-aeeb-0f621b0cf30f)

**Comment by a-nau** [comment]
Hi @DrK2B, unfortunately, [lanelet2](https://pypi.org/project/lanelet2/) is only compatible with Linux. Thus, we have the same limitation.
